// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SaasCommerce.BuildingBlocks.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202605220003_OperatingExpenses")]
public partial class OperatingExpenses : Migration
{
  protected override void Up(MigrationBuilder migrationBuilder)
  {
    // ── expense_categories ───────────────────────────────────────────────────
    migrationBuilder.CreateTable(
      name: "expense_categories",
      schema: "sales",
      columns: table => new
      {
        Id = table.Column<Guid>(type: "uuid", nullable: false),
        BusinessId = table.Column<Guid>(type: "uuid", nullable: false),
        Name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
        IsActive = table.Column<bool>(type: "boolean", nullable: false, defaultValue: true),
        CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
        UpdatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
      },
      constraints: table =>
      {
        table.PrimaryKey("PK_expense_categories", x => x.Id);
      });

    migrationBuilder.CreateIndex(
      name: "IX_expense_categories_BusinessId_Id",
      schema: "sales",
      table: "expense_categories",
      columns: ["BusinessId", "Id"],
      unique: true);

    migrationBuilder.CreateIndex(
      name: "IX_expense_categories_BusinessId_Name",
      schema: "sales",
      table: "expense_categories",
      columns: ["BusinessId", "Name"],
      unique: true);

    migrationBuilder.CreateIndex(
      name: "IX_expense_categories_BusinessId_IsActive",
      schema: "sales",
      table: "expense_categories",
      columns: ["BusinessId", "IsActive"]);

    // ── operating_expenses ───────────────────────────────────────────────────
    migrationBuilder.CreateTable(
      name: "operating_expenses",
      schema: "sales",
      columns: table => new
      {
        Id = table.Column<Guid>(type: "uuid", nullable: false),
        BusinessId = table.Column<Guid>(type: "uuid", nullable: false),
        BranchId = table.Column<Guid>(type: "uuid", nullable: false),
        UserId = table.Column<Guid>(type: "uuid", nullable: false),
        CategoryId = table.Column<Guid>(type: "uuid", nullable: false),
        Description = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
        Amount = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        PaymentMethod = table.Column<string>(type: "character varying(40)", maxLength: 40, nullable: false),
        Status = table.Column<string>(type: "character varying(40)", maxLength: 40, nullable: false, defaultValue: "Pending"),
        ExpenseDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
        Notes = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: true),
        CashSessionId = table.Column<Guid>(type: "uuid", nullable: true),
        CashMovementId = table.Column<Guid>(type: "uuid", nullable: true),
        PaidAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
        PaidByUserId = table.Column<Guid>(type: "uuid", nullable: true),
        CancelledAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
        CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
        UpdatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
      },
      constraints: table =>
      {
        table.PrimaryKey("PK_operating_expenses", x => x.Id);
      });

    migrationBuilder.CreateIndex(
      name: "IX_operating_expenses_BusinessId_Id",
      schema: "sales",
      table: "operating_expenses",
      columns: ["BusinessId", "Id"],
      unique: true);

    migrationBuilder.CreateIndex(
      name: "IX_operating_expenses_BusinessId_BranchId_Status",
      schema: "sales",
      table: "operating_expenses",
      columns: ["BusinessId", "BranchId", "Status"]);

    migrationBuilder.CreateIndex(
      name: "IX_operating_expenses_BusinessId_CategoryId",
      schema: "sales",
      table: "operating_expenses",
      columns: ["BusinessId", "CategoryId"]);

    migrationBuilder.CreateIndex(
      name: "IX_operating_expenses_BusinessId_ExpenseDate",
      schema: "sales",
      table: "operating_expenses",
      columns: ["BusinessId", "ExpenseDate"]);

    migrationBuilder.CreateIndex(
      name: "IX_operating_expenses_BusinessId_Status_ExpenseDate",
      schema: "sales",
      table: "operating_expenses",
      columns: ["BusinessId", "Status", "ExpenseDate"]);
  }

  protected override void Down(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.DropTable(name: "operating_expenses", schema: "sales");
    migrationBuilder.DropTable(name: "expense_categories", schema: "sales");
  }
}
