// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SaasCommerce.BuildingBlocks.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202605180001_BillingInvoices")]
public partial class BillingInvoices : Migration
{
  protected override void Up(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.EnsureSchema(name: "billing");

    migrationBuilder.CreateTable(
      name: "invoices",
      schema: "billing",
      columns: table => new
      {
        Id = table.Column<Guid>(type: "uuid", nullable: false),
        BusinessId = table.Column<Guid>(type: "uuid", nullable: false),
        BranchId = table.Column<Guid>(type: "uuid", nullable: false),
        SaleId = table.Column<Guid>(type: "uuid", nullable: false),
        CustomerId = table.Column<Guid>(type: "uuid", nullable: true),
        Sequence = table.Column<int>(type: "integer", nullable: false),
        InvoiceNumber = table.Column<string>(type: "character varying(32)", maxLength: 32, nullable: false),
        Subtotal = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        DiscountTotal = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        TaxTotal = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        Total = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        Status = table.Column<string>(type: "character varying(40)", maxLength: 40, nullable: false),
        CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
        UpdatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
        CancelledAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true)
      },
      constraints: table =>
      {
        table.PrimaryKey("pk_invoices", invoice => invoice.Id);
      });

    migrationBuilder.CreateIndex(
      name: "ix_invoices_business_id",
      schema: "billing",
      table: "invoices",
      column: "BusinessId");

    migrationBuilder.CreateIndex(
      name: "ix_invoices_business_id_created_at",
      schema: "billing",
      table: "invoices",
      columns: ["BusinessId", "CreatedAt"]);

    migrationBuilder.CreateIndex(
      name: "ix_invoices_business_id_invoice_number",
      schema: "billing",
      table: "invoices",
      columns: ["BusinessId", "InvoiceNumber"],
      unique: true);

    migrationBuilder.CreateIndex(
      name: "ix_invoices_business_id_sale_id",
      schema: "billing",
      table: "invoices",
      columns: ["BusinessId", "SaleId"],
      unique: true);

    migrationBuilder.Sql(
      """
      ALTER TABLE billing.invoices
        ADD CONSTRAINT ck_invoices_sequence_positive CHECK ("Sequence" > 0);

      ALTER TABLE billing.invoices
        ADD CONSTRAINT ck_invoices_totals_non_negative CHECK (
          "Subtotal" >= 0 AND
          "DiscountTotal" >= 0 AND
          "TaxTotal" >= 0 AND
          "Total" >= 0);
      """);
  }

  protected override void Down(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.DropTable(name: "invoices", schema: "billing");
  }
}
