// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SaasCommerce.BuildingBlocks.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202606040001_SplitCustomerName")]
public partial class SplitCustomerName : Migration
{
  protected override void Up(MigrationBuilder migrationBuilder)
  {
    // Add new columns (nullable first for the data migration)
    migrationBuilder.AddColumn<string>(
      name: "FirstName",
      schema: "customers",
      table: "customers",
      type: "character varying(80)",
      maxLength: 80,
      nullable: true);

    migrationBuilder.AddColumn<string>(
      name: "LastName",
      schema: "customers",
      table: "customers",
      type: "character varying(80)",
      maxLength: 80,
      nullable: true);

    // Populate: first word → FirstName, rest → LastName
    migrationBuilder.Sql("""
      UPDATE customers.customers
      SET "FirstName" = SPLIT_PART("FullName", ' ', 1),
          "LastName"  = CASE
            WHEN POSITION(' ' IN "FullName") > 0
            THEN TRIM(SUBSTRING("FullName" FROM POSITION(' ' IN "FullName") + 1))
            ELSE SPLIT_PART("FullName", ' ', 1)
          END
      """);

    // Make NOT NULL
    migrationBuilder.AlterColumn<string>(
      name: "FirstName",
      schema: "customers",
      table: "customers",
      type: "character varying(80)",
      maxLength: 80,
      nullable: false,
      defaultValue: "");

    migrationBuilder.AlterColumn<string>(
      name: "LastName",
      schema: "customers",
      table: "customers",
      type: "character varying(80)",
      maxLength: 80,
      nullable: false,
      defaultValue: "");

    // Update SearchName to use FirstName + LastName
    migrationBuilder.Sql("""
      UPDATE customers.customers
      SET "SearchName" = UPPER(CONCAT("FirstName", ' ', "LastName"))
      """);

    // Drop old FullName index (IF EXISTS — name may vary by environment)
    migrationBuilder.Sql("""
      DROP INDEX IF EXISTS customers."IX_customers_BusinessId_FullName";
      """);

    migrationBuilder.DropColumn(
      name: "FullName",
      schema: "customers",
      table: "customers");
  }

  protected override void Down(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.AddColumn<string>(
      name: "FullName",
      schema: "customers",
      table: "customers",
      type: "character varying(160)",
      maxLength: 160,
      nullable: false,
      defaultValue: "");

    migrationBuilder.Sql("""
      UPDATE customers.customers
      SET "FullName" = CONCAT("FirstName", ' ', "LastName")
      """);

    migrationBuilder.CreateIndex(
      name: "IX_customers_BusinessId_FullName",
      schema: "customers",
      table: "customers",
      columns: ["BusinessId", "FullName"]);

    migrationBuilder.DropColumn(name: "FirstName", schema: "customers", table: "customers");
    migrationBuilder.DropColumn(name: "LastName", schema: "customers", table: "customers");
  }
}
