// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SaasCommerce.BuildingBlocks.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202605150003_SettingsProfile")]
public partial class SettingsProfile : Migration
{
  protected override void Up(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.AddColumn<string>(
      name: "Phone",
      schema: "identity",
      table: "users",
      type: "character varying(40)",
      maxLength: 40,
      nullable: true);

    migrationBuilder.AddColumn<DateTimeOffset>(
      name: "UpdatedAt",
      schema: "identity",
      table: "users",
      type: "timestamp with time zone",
      nullable: false,
      defaultValueSql: "CURRENT_TIMESTAMP");

    migrationBuilder.AddColumn<DateTimeOffset>(
      name: "UpdatedAt",
      schema: "tenancy",
      table: "businesses",
      type: "timestamp with time zone",
      nullable: false,
      defaultValueSql: "CURRENT_TIMESTAMP");

    migrationBuilder.AddColumn<string>(
      name: "Address",
      schema: "tenancy",
      table: "branches",
      type: "character varying(240)",
      maxLength: 240,
      nullable: true);

    migrationBuilder.AddColumn<string>(
      name: "Phone",
      schema: "tenancy",
      table: "branches",
      type: "character varying(40)",
      maxLength: 40,
      nullable: true);

    migrationBuilder.AddColumn<DateTimeOffset>(
      name: "UpdatedAt",
      schema: "tenancy",
      table: "branches",
      type: "timestamp with time zone",
      nullable: false,
      defaultValueSql: "CURRENT_TIMESTAMP");
  }

  protected override void Down(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.DropColumn(name: "Phone", schema: "identity", table: "users");
    migrationBuilder.DropColumn(name: "UpdatedAt", schema: "identity", table: "users");
    migrationBuilder.DropColumn(name: "UpdatedAt", schema: "tenancy", table: "businesses");
    migrationBuilder.DropColumn(name: "Address", schema: "tenancy", table: "branches");
    migrationBuilder.DropColumn(name: "Phone", schema: "tenancy", table: "branches");
    migrationBuilder.DropColumn(name: "UpdatedAt", schema: "tenancy", table: "branches");
  }
}
