// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SaasCommerce.BuildingBlocks.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202605180002_SecurityAuditLog")]
public partial class SecurityAuditLog : Migration
{
  protected override void Up(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.EnsureSchema(name: "identity");

    migrationBuilder.CreateTable(
      name: "audit_logs",
      schema: "identity",
      columns: table => new
      {
        id = table.Column<Guid>(type: "uuid", nullable: false),
        business_id = table.Column<Guid>(type: "uuid", nullable: false),
        user_id = table.Column<Guid>(type: "uuid", nullable: true),
        action = table.Column<string>(type: "character varying(120)", maxLength: 120, nullable: false),
        entity_name = table.Column<string>(type: "character varying(80)", maxLength: 80, nullable: false),
        entity_id = table.Column<Guid>(type: "uuid", nullable: true),
        description = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
        ip_address = table.Column<string>(type: "character varying(45)", maxLength: 45, nullable: true),
        created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
      },
      constraints: table =>
      {
        table.PrimaryKey("pk_audit_logs", x => x.id);
      });

    migrationBuilder.CreateIndex(
      name: "ix_audit_logs_business_id",
      schema: "identity",
      table: "audit_logs",
      column: "business_id");

    migrationBuilder.CreateIndex(
      name: "ix_audit_logs_business_id_created_at",
      schema: "identity",
      table: "audit_logs",
      columns: ["business_id", "created_at"]);

    migrationBuilder.CreateIndex(
      name: "ix_audit_logs_business_id_user_id",
      schema: "identity",
      table: "audit_logs",
      columns: ["business_id", "user_id"]);
  }

  protected override void Down(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.DropTable(
      name: "audit_logs",
      schema: "identity");
  }
}
