// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SaasCommerce.BuildingBlocks.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202605210001_InventoryTransfers")]
public partial class InventoryTransfers : Migration
{
  protected override void Up(MigrationBuilder migrationBuilder)
  {
    // ── Branch.Code ─────────────────────────────────────────────────────────
    migrationBuilder.AddColumn<string>(
      name: "Code",
      schema: "tenancy",
      table: "branches",
      maxLength: 20,
      nullable: false,
      defaultValue: "PRINCIPAL");

    // Back-fill existing branches with a derived code before making it unique
    migrationBuilder.Sql(@"
      UPDATE tenancy.branches
      SET ""Code"" = UPPER(SUBSTRING(REGEXP_REPLACE(""Name"", '[^A-Za-z0-9]', '', 'g'), 1, 20))
      WHERE ""Code"" = 'PRINCIPAL'
    ");

    migrationBuilder.CreateIndex(
      name: "IX_branches_BusinessId_Code",
      schema: "tenancy",
      table: "branches",
      columns: ["BusinessId", "Code"],
      unique: true);

    migrationBuilder.CreateIndex(
      name: "IX_branches_BusinessId_IsActive",
      schema: "tenancy",
      table: "branches",
      columns: ["BusinessId", "IsActive"]);

    migrationBuilder.CreateIndex(
      name: "IX_branches_BusinessId",
      schema: "tenancy",
      table: "branches",
      column: "BusinessId");

    // ── InventoryMovement.TransferId ─────────────────────────────────────────
    migrationBuilder.AddColumn<Guid>(
      name: "TransferId",
      schema: "inventory",
      table: "inventory_movements",
      nullable: true);

    migrationBuilder.CreateIndex(
      name: "IX_inventory_movements_BusinessId_TransferId",
      schema: "inventory",
      table: "inventory_movements",
      columns: ["BusinessId", "TransferId"]);

    // ── inventory_transfers ──────────────────────────────────────────────────
    migrationBuilder.CreateTable(
      name: "inventory_transfers",
      schema: "inventory",
      columns: table => new
      {
        Id = table.Column<Guid>(nullable: false),
        BusinessId = table.Column<Guid>(nullable: false),
        SourceBranchId = table.Column<Guid>(nullable: false),
        TargetBranchId = table.Column<Guid>(nullable: false),
        CreatedByUserId = table.Column<Guid>(nullable: false),
        Status = table.Column<string>(maxLength: 32, nullable: false),
        Note = table.Column<string>(maxLength: 500, nullable: true),
        FailureReason = table.Column<string>(maxLength: 1000, nullable: true),
        CreatedAt = table.Column<DateTimeOffset>(nullable: false),
        UpdatedAt = table.Column<DateTimeOffset>(nullable: false)
      },
      constraints: table =>
      {
        table.PrimaryKey("PK_inventory_transfers", x => x.Id);
      });

    migrationBuilder.CreateIndex(
      name: "IX_inventory_transfers_BusinessId",
      schema: "inventory",
      table: "inventory_transfers",
      column: "BusinessId");

    migrationBuilder.CreateIndex(
      name: "IX_inventory_transfers_BusinessId_SourceBranchId",
      schema: "inventory",
      table: "inventory_transfers",
      columns: ["BusinessId", "SourceBranchId"]);

    migrationBuilder.CreateIndex(
      name: "IX_inventory_transfers_BusinessId_TargetBranchId",
      schema: "inventory",
      table: "inventory_transfers",
      columns: ["BusinessId", "TargetBranchId"]);

    migrationBuilder.CreateIndex(
      name: "IX_inventory_transfers_BusinessId_Status",
      schema: "inventory",
      table: "inventory_transfers",
      columns: ["BusinessId", "Status"]);

    migrationBuilder.CreateIndex(
      name: "IX_inventory_transfers_BusinessId_CreatedAt",
      schema: "inventory",
      table: "inventory_transfers",
      columns: ["BusinessId", "CreatedAt"]);

    // ── inventory_transfer_items ─────────────────────────────────────────────
    migrationBuilder.CreateTable(
      name: "inventory_transfer_items",
      schema: "inventory",
      columns: table => new
      {
        TransferId = table.Column<Guid>(nullable: false),
        ProductId = table.Column<Guid>(nullable: false),
        Quantity = table.Column<decimal>(precision: 18, scale: 3, nullable: false)
      },
      constraints: table =>
      {
        table.PrimaryKey("PK_inventory_transfer_items", x => new { x.TransferId, x.ProductId });
        table.ForeignKey(
          name: "FK_inventory_transfer_items_inventory_transfers_TransferId",
          column: x => x.TransferId,
          principalSchema: "inventory",
          principalTable: "inventory_transfers",
          principalColumn: "Id",
          onDelete: ReferentialAction.Cascade);
      });

    migrationBuilder.CreateIndex(
      name: "IX_inventory_transfer_items_TransferId",
      schema: "inventory",
      table: "inventory_transfer_items",
      column: "TransferId");
  }

  protected override void Down(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.DropTable(name: "inventory_transfer_items", schema: "inventory");
    migrationBuilder.DropTable(name: "inventory_transfers", schema: "inventory");

    migrationBuilder.DropIndex(
      name: "IX_inventory_movements_BusinessId_TransferId",
      schema: "inventory",
      table: "inventory_movements");

    migrationBuilder.DropColumn(name: "TransferId", schema: "inventory", table: "inventory_movements");

    migrationBuilder.DropIndex(
      name: "IX_branches_BusinessId_Code",
      schema: "tenancy",
      table: "branches");

    migrationBuilder.DropIndex(
      name: "IX_branches_BusinessId_IsActive",
      schema: "tenancy",
      table: "branches");

    migrationBuilder.DropIndex(
      name: "IX_branches_BusinessId",
      schema: "tenancy",
      table: "branches");

    migrationBuilder.DropColumn(name: "Code", schema: "tenancy", table: "branches");
  }
}
