// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SaasCommerce.BuildingBlocks.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202605230003_AddOperationalNotificationTable")]
public partial class AddOperationalNotificationTable : Migration
{
  protected override void Up(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.EnsureSchema(name: "notifications");

    migrationBuilder.CreateTable(
      name: "operational_notifications",
      schema: "notifications",
      columns: table => new
      {
        Id = table.Column<Guid>(type: "uuid", nullable: false),
        BusinessId = table.Column<Guid>(type: "uuid", nullable: false),
        BranchId = table.Column<Guid>(type: "uuid", nullable: true),
        Type = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
        Severity = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
        Status = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
        Title = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
        Message = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: false),
        RelatedEntityId = table.Column<Guid>(type: "uuid", nullable: true),
        RelatedEntityType = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
        CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
        ReadAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
        ReadByUserId = table.Column<Guid>(type: "uuid", nullable: true),
      },
      constraints: table =>
      {
        table.PrimaryKey("PK_operational_notifications", x => x.Id);
      });

    migrationBuilder.CreateIndex(
      name: "IX_operational_notifications_BusinessId_CreatedAt",
      schema: "notifications",
      table: "operational_notifications",
      columns: ["BusinessId", "CreatedAt"]);

    migrationBuilder.CreateIndex(
      name: "IX_operational_notifications_BusinessId_Status",
      schema: "notifications",
      table: "operational_notifications",
      columns: ["BusinessId", "Status"]);

    migrationBuilder.CreateIndex(
      name: "IX_operational_notifications_BusinessId_Type",
      schema: "notifications",
      table: "operational_notifications",
      columns: ["BusinessId", "Type"]);
  }

  protected override void Down(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.DropTable(name: "operational_notifications", schema: "notifications");
  }
}
