// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SaasCommerce.BuildingBlocks.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202605230001_AddUnitCostToSaleItems")]
public partial class AddUnitCostToSaleItems : Migration
{
  protected override void Up(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.AddColumn<decimal>(
      name: "UnitCost",
      schema: "sales",
      table: "sale_items",
      type: "numeric(18,2)",
      precision: 18,
      scale: 2,
      nullable: true);
  }

  protected override void Down(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.DropColumn(
      name: "UnitCost",
      schema: "sales",
      table: "sale_items");
  }
}
