// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SaasCommerce.BuildingBlocks.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202605230002_AddDailyClosingTables")]
public partial class AddDailyClosingTables : Migration
{
  protected override void Up(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.CreateTable(
      name: "daily_closings",
      schema: "sales",
      columns: table => new
      {
        Id = table.Column<Guid>(type: "uuid", nullable: false),
        BusinessId = table.Column<Guid>(type: "uuid", nullable: false),
        BranchId = table.Column<Guid>(type: "uuid", nullable: false),
        CreatedByUserId = table.Column<Guid>(type: "uuid", nullable: false),
        ClosingDate = table.Column<DateOnly>(type: "date", nullable: false),
        Status = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
        TotalSales = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        CashSales = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        TransferSales = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        CardSales = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        CreditSales = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        SalesCount = table.Column<int>(type: "integer", nullable: false),
        CashExpected = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        CashCounted = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: true),
        CashDifference = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: true),
        TotalExpenses = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        TotalCost = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        GrossProfit = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        EstimatedNetProfit = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        GrossMarginPercent = table.Column<decimal>(type: "numeric(8,2)", precision: 8, scale: 2, nullable: false),
        NetMarginPercent = table.Column<decimal>(type: "numeric(8,2)", precision: 8, scale: 2, nullable: false),
        NewCreditsAmount = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        NewCreditsCount = table.Column<int>(type: "integer", nullable: false),
        CreditPaymentsReceived = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        Notes = table.Column<string>(type: "character varying(2000)", maxLength: 2000, nullable: true),
        CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
        ClosedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
        ClosedByUserId = table.Column<Guid>(type: "uuid", nullable: true),
        UpdatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
      },
      constraints: table =>
      {
        table.PrimaryKey("PK_daily_closings", x => x.Id);
      });

    migrationBuilder.CreateTable(
      name: "daily_closing_alerts",
      schema: "sales",
      columns: table => new
      {
        Id = table.Column<Guid>(type: "uuid", nullable: false),
        DailyClosingId = table.Column<Guid>(type: "uuid", nullable: false),
        AlertType = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
        Message = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
        EstimatedImpact = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: true),
      },
      constraints: table =>
      {
        table.PrimaryKey("PK_daily_closing_alerts", x => x.Id);
        table.ForeignKey(
          name: "FK_daily_closing_alerts_daily_closings_DailyClosingId",
          column: x => x.DailyClosingId,
          principalSchema: "sales",
          principalTable: "daily_closings",
          principalColumn: "Id",
          onDelete: ReferentialAction.Cascade);
      });

    // Indexes for daily_closings
    migrationBuilder.CreateIndex(
      name: "IX_daily_closings_BusinessId_BranchId_ClosingDate",
      schema: "sales",
      table: "daily_closings",
      columns: ["BusinessId", "BranchId", "ClosingDate"],
      unique: true);

    migrationBuilder.CreateIndex(
      name: "IX_daily_closings_BusinessId_ClosingDate",
      schema: "sales",
      table: "daily_closings",
      columns: ["BusinessId", "ClosingDate"]);

    migrationBuilder.CreateIndex(
      name: "IX_daily_closings_BusinessId_Id",
      schema: "sales",
      table: "daily_closings",
      columns: ["BusinessId", "Id"],
      unique: true);

    migrationBuilder.CreateIndex(
      name: "IX_daily_closings_BusinessId_Status",
      schema: "sales",
      table: "daily_closings",
      columns: ["BusinessId", "Status"]);

    // Indexes for daily_closing_alerts
    migrationBuilder.CreateIndex(
      name: "IX_daily_closing_alerts_DailyClosingId",
      schema: "sales",
      table: "daily_closing_alerts",
      column: "DailyClosingId");
  }

  protected override void Down(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.DropTable(name: "daily_closing_alerts", schema: "sales");
    migrationBuilder.DropTable(name: "daily_closings", schema: "sales");
  }
}
