// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SaasCommerce.BuildingBlocks.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202606030001_AddProductImageUrl")]
public partial class AddProductImageUrl : Migration
{
  protected override void Up(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.AddColumn<string>(
      name: "ImageUrl",
      schema: "catalog",
      table: "products",
      type: "character varying(512)",
      maxLength: 512,
      nullable: true);
  }

  protected override void Down(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.DropColumn(
      name: "ImageUrl",
      schema: "catalog",
      table: "products");
  }
}
