// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SaasCommerce.BuildingBlocks.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202605190002_AuditExtensions")]
public partial class AuditExtensions : Migration
{
  protected override void Up(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.AddColumn<Guid>(
      name: "correlation_id", schema: "identity", table: "audit_logs",
      nullable: true);
    migrationBuilder.AddColumn<string>(
      name: "user_agent", schema: "identity", table: "audit_logs",
      maxLength: 512, nullable: true);
    migrationBuilder.AddColumn<string>(
      name: "metadata_json", schema: "identity", table: "audit_logs",
      maxLength: 2000, nullable: true);
    migrationBuilder.CreateIndex(
      name: "ix_audit_logs_business_id_correlation_id",
      schema: "identity", table: "audit_logs",
      columns: ["business_id", "correlation_id"]);
  }

  protected override void Down(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.DropIndex(name: "ix_audit_logs_business_id_correlation_id", schema: "identity", table: "audit_logs");
    migrationBuilder.DropColumn(name: "correlation_id", schema: "identity", table: "audit_logs");
    migrationBuilder.DropColumn(name: "user_agent", schema: "identity", table: "audit_logs");
    migrationBuilder.DropColumn(name: "metadata_json", schema: "identity", table: "audit_logs");
  }
}
