// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SaasCommerce.BuildingBlocks.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202605170001_CustomersSalesApi")]
public partial class CustomersSalesApi : Migration
{
  protected override void Up(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.EnsureSchema(name: "customers");

    migrationBuilder.AddColumn<Guid>(
      name: "CustomerId",
      schema: "sales",
      table: "sales",
      type: "uuid",
      nullable: true);

    migrationBuilder.CreateTable(
      name: "customers",
      schema: "customers",
      columns: table => new
      {
        Id = table.Column<Guid>(type: "uuid", nullable: false),
        BusinessId = table.Column<Guid>(type: "uuid", nullable: false),
        FullName = table.Column<string>(type: "character varying(160)", maxLength: 160, nullable: false),
        SearchName = table.Column<string>(type: "character varying(160)", maxLength: 160, nullable: false),
        Phone = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: true),
        Email = table.Column<string>(type: "character varying(320)", maxLength: 320, nullable: true),
        IsActive = table.Column<bool>(type: "boolean", nullable: false),
        CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
        UpdatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
        DeactivatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true)
      },
      constraints: table =>
      {
        table.PrimaryKey("pk_customers", x => x.Id);
      });

    migrationBuilder.CreateIndex(
      name: "ix_sales_business_id_customer_id",
      schema: "sales",
      table: "sales",
      columns: ["BusinessId", "CustomerId"]);

    migrationBuilder.CreateIndex(
      name: "ix_customers_business_id_full_name",
      schema: "customers",
      table: "customers",
      columns: ["BusinessId", "FullName"]);

    migrationBuilder.CreateIndex(
      name: "ix_customers_business_id_is_active",
      schema: "customers",
      table: "customers",
      columns: ["BusinessId", "IsActive"]);

    migrationBuilder.CreateIndex(
      name: "ix_customers_business_id_search_name",
      schema: "customers",
      table: "customers",
      columns: ["BusinessId", "SearchName"]);
  }

  protected override void Down(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.DropTable(name: "customers", schema: "customers");

    migrationBuilder.DropIndex(
      name: "ix_sales_business_id_customer_id",
      schema: "sales",
      table: "sales");

    migrationBuilder.DropColumn(
      name: "CustomerId",
      schema: "sales",
      table: "sales");
  }
}
