// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SaasCommerce.BuildingBlocks.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202605200001_BusinessSettings")]
public partial class BusinessSettings : Migration
{
  protected override void Up(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.EnsureSchema(name: "settings");

    // ── business_settings ────────────────────────────────────────────────────
    migrationBuilder.CreateTable(
      name: "business_settings",
      schema: "settings",
      columns: table => new
      {
        business_id = table.Column<Guid>(nullable: false),
        commercial_name = table.Column<string>(maxLength: 200, nullable: true),
        legal_name = table.Column<string>(maxLength: 200, nullable: true),
        rnc = table.Column<string>(maxLength: 20, nullable: true),
        phone = table.Column<string>(maxLength: 30, nullable: true),
        email = table.Column<string>(maxLength: 254, nullable: true),
        address = table.Column<string>(maxLength: 500, nullable: true),
        currency = table.Column<string>(maxLength: 3, nullable: false, defaultValue: "DOP"),
        timezone = table.Column<string>(maxLength: 80, nullable: false, defaultValue: "America/Santo_Domingo"),
        logo_url = table.Column<string>(maxLength: 2048, nullable: true),
        receipt_footer_text = table.Column<string>(maxLength: 500, nullable: true),
        updated_by = table.Column<Guid>(nullable: false),
        updated_at = table.Column<DateTimeOffset>(nullable: false)
      },
      constraints: table =>
      {
        table.PrimaryKey("pk_business_settings", x => x.business_id);
      });

    // ── sales_settings ───────────────────────────────────────────────────────
    migrationBuilder.CreateTable(
      name: "sales_settings",
      schema: "settings",
      columns: table => new
      {
        business_id = table.Column<Guid>(nullable: false),
        allow_negative_stock = table.Column<bool>(nullable: false, defaultValue: false),
        allow_discounts = table.Column<bool>(nullable: false, defaultValue: true),
        require_customer_for_credit_sale = table.Column<bool>(nullable: false, defaultValue: true),
        default_payment_method = table.Column<string>(maxLength: 50, nullable: true),
        enable_receipt_print_after_sale = table.Column<bool>(nullable: false, defaultValue: false),
        enable_invoice_auto_generation = table.Column<bool>(nullable: false, defaultValue: true),
        updated_by = table.Column<Guid>(nullable: false),
        updated_at = table.Column<DateTimeOffset>(nullable: false)
      },
      constraints: table =>
      {
        table.PrimaryKey("pk_sales_settings", x => x.business_id);
      });

    // ── inventory_settings ───────────────────────────────────────────────────
    migrationBuilder.CreateTable(
      name: "inventory_settings",
      schema: "settings",
      columns: table => new
      {
        business_id = table.Column<Guid>(nullable: false),
        enable_low_stock_alerts = table.Column<bool>(nullable: false, defaultValue: true),
        default_low_stock_threshold = table.Column<decimal>(type: "numeric(18,4)", nullable: false, defaultValue: 5m),
        require_reason_for_inventory_adjustment = table.Column<bool>(nullable: false, defaultValue: false),
        allow_inventory_transfer_between_branches = table.Column<bool>(nullable: false, defaultValue: false),
        updated_by = table.Column<Guid>(nullable: false),
        updated_at = table.Column<DateTimeOffset>(nullable: false)
      },
      constraints: table =>
      {
        table.PrimaryKey("pk_inventory_settings", x => x.business_id);
      });

    // ── billing_settings ─────────────────────────────────────────────────────
    migrationBuilder.CreateTable(
      name: "billing_settings",
      schema: "settings",
      columns: table => new
      {
        business_id = table.Column<Guid>(nullable: false),
        receipt_header_text = table.Column<string>(maxLength: 500, nullable: true),
        receipt_footer_text = table.Column<string>(maxLength: 500, nullable: true),
        show_logo_on_receipt = table.Column<bool>(nullable: false, defaultValue: false),
        show_rnc_on_receipt = table.Column<bool>(nullable: false, defaultValue: false),
        enable_invoice_auto_generation = table.Column<bool>(nullable: false, defaultValue: true),
        invoice_prefix = table.Column<string>(maxLength: 10, nullable: false, defaultValue: "RI"),
        invoice_sequence_start = table.Column<int>(nullable: false, defaultValue: 1),
        updated_by = table.Column<Guid>(nullable: false),
        updated_at = table.Column<DateTimeOffset>(nullable: false)
      },
      constraints: table =>
      {
        table.PrimaryKey("pk_billing_settings", x => x.business_id);
      });
  }

  protected override void Down(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.DropTable(name: "billing_settings", schema: "settings");
    migrationBuilder.DropTable(name: "inventory_settings", schema: "settings");
    migrationBuilder.DropTable(name: "sales_settings", schema: "settings");
    migrationBuilder.DropTable(name: "business_settings", schema: "settings");
  }
}
