// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SaasCommerce.BuildingBlocks.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202606040002_AddPosCartTables")]
public partial class AddPosCartTables : Migration
{
  protected override void Up(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.CreateTable(
      name: "pos_carts",
      schema: "sales",
      columns: table => new
      {
        Id = table.Column<Guid>(type: "uuid", nullable: false),
        BusinessId = table.Column<Guid>(type: "uuid", nullable: false),
        UserId = table.Column<Guid>(type: "uuid", nullable: false),
        UpdatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
      },
      constraints: table => table.PrimaryKey("PK_pos_carts", x => x.Id));

    migrationBuilder.CreateTable(
      name: "pos_cart_items",
      schema: "sales",
      columns: table => new
      {
        Id = table.Column<Guid>(type: "uuid", nullable: false),
        CartId = table.Column<Guid>(type: "uuid", nullable: false),
        ProductId = table.Column<Guid>(type: "uuid", nullable: false),
        Name = table.Column<string>(type: "character varying(180)", maxLength: 180, nullable: false),
        Sku = table.Column<string>(type: "character varying(80)", maxLength: 80, nullable: false),
        UnitPrice = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        Quantity = table.Column<int>(type: "integer", nullable: false),
      },
      constraints: table =>
      {
        table.PrimaryKey("PK_pos_cart_items", x => x.Id);
        table.ForeignKey(
          name: "FK_pos_cart_items_pos_carts_CartId",
          column: x => x.CartId,
          principalSchema: "sales",
          principalTable: "pos_carts",
          principalColumn: "Id",
          onDelete: ReferentialAction.Cascade);
      });

    migrationBuilder.CreateIndex(
      name: "IX_pos_carts_BusinessId_UserId",
      schema: "sales",
      table: "pos_carts",
      columns: ["BusinessId", "UserId"],
      unique: true);

    migrationBuilder.CreateIndex(
      name: "IX_pos_cart_items_CartId_ProductId",
      schema: "sales",
      table: "pos_cart_items",
      columns: ["CartId", "ProductId"],
      unique: true);
  }

  protected override void Down(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.DropTable(name: "pos_cart_items", schema: "sales");
    migrationBuilder.DropTable(name: "pos_carts", schema: "sales");
  }
}
