// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SaasCommerce.BuildingBlocks.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202605160003_SalesSagaFlow")]
public partial class SalesSagaFlow : Migration
{
  protected override void Up(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.EnsureSchema(name: "sales");

    migrationBuilder.DropIndex(
      name: "ix_sale_saga_states_sale_id",
      table: "sale_saga_states");

    migrationBuilder.AddColumn<int>(
      name: "Version",
      table: "sale_saga_states",
      type: "integer",
      nullable: false,
      defaultValue: 0);

    migrationBuilder.CreateTable(
      name: "sales",
      schema: "sales",
      columns: table => new
      {
        Id = table.Column<Guid>(type: "uuid", nullable: false),
        BusinessId = table.Column<Guid>(type: "uuid", nullable: false),
        BranchId = table.Column<Guid>(type: "uuid", nullable: false),
        UserId = table.Column<Guid>(type: "uuid", nullable: false),
        Status = table.Column<string>(type: "character varying(40)", maxLength: 40, nullable: false),
        PaymentMethod = table.Column<string>(type: "character varying(80)", maxLength: 80, nullable: false),
        Total = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
        UpdatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
        CompletedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
        FailedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
        CancelledAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
        FailureReason = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: true),
        CancellationReason = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: true)
      },
      constraints: table =>
      {
        table.PrimaryKey("pk_sales", x => x.Id);
      });

    migrationBuilder.CreateTable(
      name: "sale_items",
      schema: "sales",
      columns: table => new
      {
        Id = table.Column<Guid>(type: "uuid", nullable: false),
        SaleId = table.Column<Guid>(type: "uuid", nullable: false),
        ProductId = table.Column<Guid>(type: "uuid", nullable: false),
        Quantity = table.Column<decimal>(type: "numeric(18,3)", precision: 18, scale: 3, nullable: false),
        UnitPrice = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false)
      },
      constraints: table =>
      {
        table.PrimaryKey("pk_sale_items", x => x.Id);
        table.ForeignKey(
          name: "fk_sale_items_sales_sale_id",
          column: x => x.SaleId,
          principalSchema: "sales",
          principalTable: "sales",
          principalColumn: "Id",
          onDelete: ReferentialAction.Cascade);
      });

    migrationBuilder.CreateIndex(
      name: "ix_sale_items_sale_id_product_id",
      schema: "sales",
      table: "sale_items",
      columns: ["SaleId", "ProductId"]);

    migrationBuilder.CreateIndex(
      name: "ix_sale_items_sale_id",
      schema: "sales",
      table: "sale_items",
      column: "SaleId");

    migrationBuilder.CreateIndex(
      name: "ix_sales_business_id_branch_id_status",
      schema: "sales",
      table: "sales",
      columns: ["BusinessId", "BranchId", "Status"]);

    migrationBuilder.CreateIndex(
      name: "ix_sales_business_id_id",
      schema: "sales",
      table: "sales",
      columns: ["BusinessId", "Id"],
      unique: true);

    migrationBuilder.CreateIndex(
      name: "ix_sale_saga_states_business_id",
      table: "sale_saga_states",
      column: "BusinessId");

    migrationBuilder.CreateIndex(
      name: "ix_sale_saga_states_business_id_sale_id",
      table: "sale_saga_states",
      columns: ["BusinessId", "SaleId"],
      unique: true);

    migrationBuilder.CreateIndex(
      name: "ix_sale_saga_states_current_state",
      table: "sale_saga_states",
      column: "CurrentState");

    migrationBuilder.CreateIndex(
      name: "ix_sale_saga_states_sale_id",
      table: "sale_saga_states",
      column: "SaleId");
  }

  protected override void Down(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.DropTable(name: "sale_items", schema: "sales");
    migrationBuilder.DropTable(name: "sales", schema: "sales");

    migrationBuilder.DropIndex(
      name: "ix_sale_saga_states_business_id",
      table: "sale_saga_states");

    migrationBuilder.DropIndex(
      name: "ix_sale_saga_states_business_id_sale_id",
      table: "sale_saga_states");

    migrationBuilder.DropIndex(
      name: "ix_sale_saga_states_current_state",
      table: "sale_saga_states");

    migrationBuilder.DropIndex(
      name: "ix_sale_saga_states_sale_id",
      table: "sale_saga_states");

    migrationBuilder.DropColumn(
      name: "Version",
      table: "sale_saga_states");

    migrationBuilder.CreateIndex(
      name: "ix_sale_saga_states_sale_id",
      table: "sale_saga_states",
      column: "SaleId",
      unique: true);
  }
}
