// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SaasCommerce.BuildingBlocks.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202605220002_CashSessions")]
public partial class CashSessions : Migration
{
  protected override void Up(MigrationBuilder migrationBuilder)
  {
    // ── cash_sessions ────────────────────────────────────────────────────────
    migrationBuilder.CreateTable(
      name: "cash_sessions",
      schema: "sales",
      columns: table => new
      {
        Id = table.Column<Guid>(type: "uuid", nullable: false),
        BusinessId = table.Column<Guid>(type: "uuid", nullable: false),
        BranchId = table.Column<Guid>(type: "uuid", nullable: false),
        UserId = table.Column<Guid>(type: "uuid", nullable: false),
        Status = table.Column<string>(type: "character varying(40)", maxLength: 40, nullable: false, defaultValue: "Open"),
        OpeningBalance = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        ClosingBalance = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: true),
        Notes = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: true),
        OpenedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
        ClosedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
        UpdatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
      },
      constraints: table =>
      {
        table.PrimaryKey("PK_cash_sessions", x => x.Id);
      });

    migrationBuilder.CreateIndex(
      name: "IX_cash_sessions_BusinessId_Id",
      schema: "sales",
      table: "cash_sessions",
      columns: ["BusinessId", "Id"],
      unique: true);

    migrationBuilder.CreateIndex(
      name: "IX_cash_sessions_BusinessId_BranchId_Status",
      schema: "sales",
      table: "cash_sessions",
      columns: ["BusinessId", "BranchId", "Status"]);

    migrationBuilder.CreateIndex(
      name: "IX_cash_sessions_BusinessId_OpenedAt",
      schema: "sales",
      table: "cash_sessions",
      columns: ["BusinessId", "OpenedAt"]);

    // ── cash_movements ───────────────────────────────────────────────────────
    migrationBuilder.CreateTable(
      name: "cash_movements",
      schema: "sales",
      columns: table => new
      {
        Id = table.Column<Guid>(type: "uuid", nullable: false),
        CashSessionId = table.Column<Guid>(type: "uuid", nullable: false),
        UserId = table.Column<Guid>(type: "uuid", nullable: false),
        Type = table.Column<string>(type: "character varying(40)", maxLength: 40, nullable: false),
        Amount = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        Description = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
        CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
      },
      constraints: table =>
      {
        table.PrimaryKey("PK_cash_movements", x => x.Id);
        table.ForeignKey(
          name: "FK_cash_movements_cash_sessions_CashSessionId",
          column: x => x.CashSessionId,
          principalSchema: "sales",
          principalTable: "cash_sessions",
          principalColumn: "Id",
          onDelete: ReferentialAction.Cascade);
      });

    migrationBuilder.CreateIndex(
      name: "IX_cash_movements_CashSessionId",
      schema: "sales",
      table: "cash_movements",
      column: "CashSessionId");

    migrationBuilder.CreateIndex(
      name: "IX_cash_movements_CashSessionId_CreatedAt",
      schema: "sales",
      table: "cash_movements",
      columns: ["CashSessionId", "CreatedAt"]);
  }

  protected override void Down(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.DropTable(name: "cash_movements", schema: "sales");
    migrationBuilder.DropTable(name: "cash_sessions", schema: "sales");
  }
}
