// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SaasCommerce.BuildingBlocks.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202605170004_CustomerCredits")]
public partial class CustomerCredits : Migration
{
  protected override void Up(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.EnsureSchema(name: "customers");

    migrationBuilder.CreateTable(
      name: "customer_credit_accounts",
      schema: "customers",
      columns: table => new
      {
        Id = table.Column<Guid>(type: "uuid", nullable: false),
        BusinessId = table.Column<Guid>(type: "uuid", nullable: false),
        CustomerId = table.Column<Guid>(type: "uuid", nullable: false),
        CreditLimit = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        CurrentBalance = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        Status = table.Column<string>(type: "character varying(40)", maxLength: 40, nullable: false),
        CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
        UpdatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
      },
      constraints: table =>
      {
        table.PrimaryKey("pk_customer_credit_accounts", x => x.Id);
      });

    migrationBuilder.CreateTable(
      name: "customer_credit_movements",
      schema: "customers",
      columns: table => new
      {
        Id = table.Column<Guid>(type: "uuid", nullable: false),
        BusinessId = table.Column<Guid>(type: "uuid", nullable: false),
        CustomerId = table.Column<Guid>(type: "uuid", nullable: false),
        SaleId = table.Column<Guid>(type: "uuid", nullable: true),
        PaymentId = table.Column<Guid>(type: "uuid", nullable: true),
        Type = table.Column<string>(type: "character varying(40)", maxLength: 40, nullable: false),
        Amount = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        PreviousBalance = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        NewBalance = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        Note = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
        CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
        CreatedBy = table.Column<Guid>(type: "uuid", nullable: true)
      },
      constraints: table =>
      {
        table.PrimaryKey("pk_customer_credit_movements", x => x.Id);
      });

    migrationBuilder.CreateTable(
      name: "customer_payments",
      schema: "customers",
      columns: table => new
      {
        Id = table.Column<Guid>(type: "uuid", nullable: false),
        BusinessId = table.Column<Guid>(type: "uuid", nullable: false),
        CustomerId = table.Column<Guid>(type: "uuid", nullable: false),
        Amount = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        Note = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
        CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
        CreatedBy = table.Column<Guid>(type: "uuid", nullable: true)
      },
      constraints: table =>
      {
        table.PrimaryKey("pk_customer_payments", x => x.Id);
      });

    migrationBuilder.CreateIndex(
      name: "ix_customer_credit_accounts_business_id_customer_id",
      schema: "customers",
      table: "customer_credit_accounts",
      columns: ["BusinessId", "CustomerId"],
      unique: true);

    migrationBuilder.CreateIndex(
      name: "ix_customer_credit_movements_business_id_customer_id_created_at",
      schema: "customers",
      table: "customer_credit_movements",
      columns: ["BusinessId", "CustomerId", "CreatedAt"]);

    migrationBuilder.CreateIndex(
      name: "ix_customer_credit_movements_business_id_payment_id",
      schema: "customers",
      table: "customer_credit_movements",
      columns: ["BusinessId", "PaymentId"],
      unique: true,
      filter: "\"PaymentId\" IS NOT NULL");

    migrationBuilder.CreateIndex(
      name: "ix_customer_credit_movements_business_id_sale_id",
      schema: "customers",
      table: "customer_credit_movements",
      columns: ["BusinessId", "SaleId"],
      unique: true,
      filter: "\"SaleId\" IS NOT NULL");

    migrationBuilder.CreateIndex(
      name: "ix_customer_payments_business_id_customer_id_created_at",
      schema: "customers",
      table: "customer_payments",
      columns: ["BusinessId", "CustomerId", "CreatedAt"]);

    migrationBuilder.Sql(
      """
      ALTER TABLE customers.customer_credit_accounts
        ADD CONSTRAINT ck_customer_credit_accounts_current_balance_non_negative CHECK ("CurrentBalance" >= 0);

      ALTER TABLE customers.customer_credit_accounts
        ADD CONSTRAINT ck_customer_credit_accounts_credit_limit_non_negative CHECK ("CreditLimit" >= 0);

      ALTER TABLE customers.customer_credit_movements
        ADD CONSTRAINT ck_customer_credit_movements_amount_positive CHECK ("Amount" > 0);

      ALTER TABLE customers.customer_credit_movements
        ADD CONSTRAINT ck_customer_credit_movements_balances_non_negative CHECK ("PreviousBalance" >= 0 AND "NewBalance" >= 0);

      ALTER TABLE customers.customer_payments
        ADD CONSTRAINT ck_customer_payments_amount_positive CHECK ("Amount" > 0);
      """);
  }

  protected override void Down(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.DropTable(name: "customer_credit_movements", schema: "customers");
    migrationBuilder.DropTable(name: "customer_payments", schema: "customers");
    migrationBuilder.DropTable(name: "customer_credit_accounts", schema: "customers");
  }
}
