// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SaasCommerce.BuildingBlocks.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202605170003_PurchasingInventoryReplenishment")]
public partial class PurchasingInventoryReplenishment : Migration
{
  protected override void Up(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.EnsureSchema(name: "purchasing");

    migrationBuilder.AddColumn<Guid>(
      name: "PurchaseId",
      schema: "inventory",
      table: "inventory_movements",
      type: "uuid",
      nullable: true);

    migrationBuilder.CreateTable(
      name: "suppliers",
      schema: "purchasing",
      columns: table => new
      {
        Id = table.Column<Guid>(type: "uuid", nullable: false),
        BusinessId = table.Column<Guid>(type: "uuid", nullable: false),
        Name = table.Column<string>(type: "character varying(180)", maxLength: 180, nullable: false),
        SearchName = table.Column<string>(type: "character varying(180)", maxLength: 180, nullable: false),
        Rnc = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: true),
        Phone = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: true),
        Email = table.Column<string>(type: "character varying(320)", maxLength: 320, nullable: true),
        Address = table.Column<string>(type: "character varying(400)", maxLength: 400, nullable: true),
        IsActive = table.Column<bool>(type: "boolean", nullable: false),
        CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
        UpdatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true)
      },
      constraints: table =>
      {
        table.PrimaryKey("pk_suppliers", x => x.Id);
      });

    migrationBuilder.CreateTable(
      name: "purchases",
      schema: "purchasing",
      columns: table => new
      {
        Id = table.Column<Guid>(type: "uuid", nullable: false),
        BusinessId = table.Column<Guid>(type: "uuid", nullable: false),
        BranchId = table.Column<Guid>(type: "uuid", nullable: false),
        SupplierId = table.Column<Guid>(type: "uuid", nullable: false),
        UserId = table.Column<Guid>(type: "uuid", nullable: false),
        Status = table.Column<string>(type: "character varying(40)", maxLength: 40, nullable: false),
        SupplierInvoiceNumber = table.Column<string>(type: "character varying(80)", maxLength: 80, nullable: true),
        PurchaseDate = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
        Notes = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: true),
        Total = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
        UpdatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
        ReceivedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
        CancelledAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true)
      },
      constraints: table =>
      {
        table.PrimaryKey("pk_purchases", x => x.Id);
      });

    migrationBuilder.CreateTable(
      name: "purchase_items",
      schema: "purchasing",
      columns: table => new
      {
        Id = table.Column<Guid>(type: "uuid", nullable: false),
        PurchaseId = table.Column<Guid>(type: "uuid", nullable: false),
        ProductId = table.Column<Guid>(type: "uuid", nullable: false),
        Quantity = table.Column<decimal>(type: "numeric(18,3)", precision: 18, scale: 3, nullable: false),
        UnitCost = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false)
      },
      constraints: table =>
      {
        table.PrimaryKey("pk_purchase_items", x => x.Id);
        table.ForeignKey(
          name: "fk_purchase_items_purchases_purchase_id",
          column: x => x.PurchaseId,
          principalSchema: "purchasing",
          principalTable: "purchases",
          principalColumn: "Id",
          onDelete: ReferentialAction.Cascade);
      });

    migrationBuilder.CreateIndex(
      name: "ix_inventory_movements_business_id_branch_id_purchase_id",
      schema: "inventory",
      table: "inventory_movements",
      columns: ["BusinessId", "BranchId", "PurchaseId"]);

    migrationBuilder.CreateIndex(
      name: "ix_suppliers_business_id_is_active",
      schema: "purchasing",
      table: "suppliers",
      columns: ["BusinessId", "IsActive"]);

    migrationBuilder.CreateIndex(
      name: "ix_suppliers_business_id_name",
      schema: "purchasing",
      table: "suppliers",
      columns: ["BusinessId", "Name"]);

    migrationBuilder.CreateIndex(
      name: "ix_suppliers_business_id_rnc",
      schema: "purchasing",
      table: "suppliers",
      columns: ["BusinessId", "Rnc"]);

    migrationBuilder.CreateIndex(
      name: "ix_suppliers_business_id_search_name",
      schema: "purchasing",
      table: "suppliers",
      columns: ["BusinessId", "SearchName"]);

    migrationBuilder.CreateIndex(
      name: "ix_purchases_business_id_branch_id_status",
      schema: "purchasing",
      table: "purchases",
      columns: ["BusinessId", "BranchId", "Status"]);

    migrationBuilder.CreateIndex(
      name: "ix_purchases_business_id_id",
      schema: "purchasing",
      table: "purchases",
      columns: ["BusinessId", "Id"],
      unique: true);

    migrationBuilder.CreateIndex(
      name: "ix_purchases_business_id_purchase_date",
      schema: "purchasing",
      table: "purchases",
      columns: ["BusinessId", "PurchaseDate"]);

    migrationBuilder.CreateIndex(
      name: "ix_purchases_business_id_supplier_id",
      schema: "purchasing",
      table: "purchases",
      columns: ["BusinessId", "SupplierId"]);

    migrationBuilder.CreateIndex(
      name: "ix_purchases_business_id_supplier_invoice_number",
      schema: "purchasing",
      table: "purchases",
      columns: ["BusinessId", "SupplierInvoiceNumber"]);

    migrationBuilder.CreateIndex(
      name: "ix_purchase_items_purchase_id_product_id",
      schema: "purchasing",
      table: "purchase_items",
      columns: ["PurchaseId", "ProductId"]);
  }

  protected override void Down(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.DropTable(name: "purchase_items", schema: "purchasing");
    migrationBuilder.DropTable(name: "purchases", schema: "purchasing");
    migrationBuilder.DropTable(name: "suppliers", schema: "purchasing");

    migrationBuilder.DropIndex(
      name: "ix_inventory_movements_business_id_branch_id_purchase_id",
      schema: "inventory",
      table: "inventory_movements");

    migrationBuilder.DropColumn(
      name: "PurchaseId",
      schema: "inventory",
      table: "inventory_movements");
  }
}
