// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SaasCommerce.BuildingBlocks.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202605280001_AddInventoryMovementReturnId")]
public partial class AddInventoryMovementReturnId : Migration
{
  protected override void Up(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.AddColumn<Guid>(
      name: "ReturnId",
      schema: "inventory",
      table: "inventory_movements",
      type: "uuid",
      nullable: true);

    migrationBuilder.CreateIndex(
      name: "IX_inventory_movements_BusinessId_BranchId_ReturnId",
      schema: "inventory",
      table: "inventory_movements",
      columns: ["BusinessId", "BranchId", "ReturnId"]);
  }

  protected override void Down(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.DropIndex(
      name: "IX_inventory_movements_BusinessId_BranchId_ReturnId",
      schema: "inventory",
      table: "inventory_movements");

    migrationBuilder.DropColumn(
      name: "ReturnId",
      schema: "inventory",
      table: "inventory_movements");
  }
}
