// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SaasCommerce.BuildingBlocks.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202605150002_AccountOnboarding")]
public partial class AccountOnboarding : Migration
{
  protected override void Up(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.AddColumn<string>(
      name: "IdentificationType",
      schema: "tenancy",
      table: "businesses",
      type: "character varying(40)",
      maxLength: 40,
      nullable: true);

    migrationBuilder.AddColumn<string>(
      name: "IdentificationNumber",
      schema: "tenancy",
      table: "businesses",
      type: "character varying(40)",
      maxLength: 40,
      nullable: true);

    migrationBuilder.CreateTable(
      name: "business_phones",
      schema: "tenancy",
      columns: table => new
      {
        Id = table.Column<Guid>(type: "uuid", nullable: false),
        BusinessId = table.Column<Guid>(type: "uuid", nullable: false),
        Number = table.Column<string>(type: "character varying(40)", maxLength: 40, nullable: false),
        Label = table.Column<string>(type: "character varying(80)", maxLength: 80, nullable: true),
        IsPrimary = table.Column<bool>(type: "boolean", nullable: false),
        CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
        UpdatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true)
      },
      constraints: table =>
      {
        table.PrimaryKey("pk_business_phones", phone => phone.Id);
        table.ForeignKey(
          name: "fk_business_phones_businesses_business_id",
          column: phone => phone.BusinessId,
          principalSchema: "tenancy",
          principalTable: "businesses",
          principalColumn: "Id",
          onDelete: ReferentialAction.Cascade);
      });

    migrationBuilder.CreateIndex(
      name: "ix_businesses_identification_type_identification_number",
      schema: "tenancy",
      table: "businesses",
      columns: ["IdentificationType", "IdentificationNumber"],
      unique: true,
      filter: "\"IdentificationType\" IS NOT NULL AND \"IdentificationNumber\" IS NOT NULL");

    migrationBuilder.CreateIndex(
      name: "ix_business_phones_business_id_number",
      schema: "tenancy",
      table: "business_phones",
      columns: ["BusinessId", "Number"],
      unique: true);
  }

  protected override void Down(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.DropTable(name: "business_phones", schema: "tenancy");

    migrationBuilder.DropIndex(
      name: "ix_businesses_identification_type_identification_number",
      schema: "tenancy",
      table: "businesses");

    migrationBuilder.DropColumn(name: "IdentificationType", schema: "tenancy", table: "businesses");
    migrationBuilder.DropColumn(name: "IdentificationNumber", schema: "tenancy", table: "businesses");
  }
}
