// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SaasCommerce.BuildingBlocks.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202605260001_AddCashRegisterTables")]
public partial class AddCashRegisterTables : Migration
{
  protected override void Up(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.CreateTable(
      name: "cash_registers",
      schema: "sales",
      columns: table => new
      {
        Id = table.Column<Guid>(type: "uuid", nullable: false),
        BusinessId = table.Column<Guid>(type: "uuid", nullable: false),
        BranchId = table.Column<Guid>(type: "uuid", nullable: false),
        UserId = table.Column<Guid>(type: "uuid", nullable: false),
        Status = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
        OpeningAmount = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        Notes = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
        OpenedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
        ClosedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
        UpdatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
        CountedAmount = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: true),
        ExpectedCashAmount = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: true),
        Difference = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: true),
        DifferenceType = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: true),
        CloseNotes = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: true),
        CashSalesTotal = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        CardSalesTotal = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        TransferSalesTotal = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        CreditSalesTotal = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        CashReturnsTotal = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
      },
      constraints: table =>
      {
        table.PrimaryKey("PK_cash_registers", x => x.Id);
      });

    migrationBuilder.CreateTable(
      name: "cash_register_movements",
      schema: "sales",
      columns: table => new
      {
        Id = table.Column<Guid>(type: "uuid", nullable: false),
        CashRegisterId = table.Column<Guid>(type: "uuid", nullable: false),
        UserId = table.Column<Guid>(type: "uuid", nullable: false),
        MovementType = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false),
        Amount = table.Column<decimal>(type: "numeric(18,2)", precision: 18, scale: 2, nullable: false),
        Reason = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
        CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
      },
      constraints: table =>
      {
        table.PrimaryKey("PK_cash_register_movements", x => x.Id);
        table.ForeignKey(
          name: "FK_cash_register_movements_cash_registers_CashRegisterId",
          column: x => x.CashRegisterId,
          principalSchema: "sales",
          principalTable: "cash_registers",
          principalColumn: "Id",
          onDelete: ReferentialAction.Cascade);
      });

    migrationBuilder.CreateIndex(
      name: "IX_cash_registers_BusinessId_BranchId_Status",
      schema: "sales",
      table: "cash_registers",
      columns: ["BusinessId", "BranchId", "Status"]);

    migrationBuilder.CreateIndex(
      name: "IX_cash_registers_BusinessId_UserId_Status",
      schema: "sales",
      table: "cash_registers",
      columns: ["BusinessId", "UserId", "Status"]);

    migrationBuilder.CreateIndex(
      name: "IX_cash_registers_BusinessId_Id",
      schema: "sales",
      table: "cash_registers",
      columns: ["BusinessId", "Id"],
      unique: true);

    migrationBuilder.CreateIndex(
      name: "IX_cash_registers_BusinessId_OpenedAt",
      schema: "sales",
      table: "cash_registers",
      columns: ["BusinessId", "OpenedAt"]);

    migrationBuilder.CreateIndex(
      name: "IX_cash_register_movements_CashRegisterId",
      schema: "sales",
      table: "cash_register_movements",
      column: "CashRegisterId");
  }

  protected override void Down(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.DropTable(name: "cash_register_movements", schema: "sales");
    migrationBuilder.DropTable(name: "cash_registers", schema: "sales");
  }
}
