// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SaasCommerce.BuildingBlocks.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202605170002_InventoryAdvanced")]
public partial class InventoryAdvanced : Migration
{
  protected override void Up(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.AddColumn<Guid>(
      name: "SaleId",
      schema: "inventory",
      table: "inventory_movements",
      type: "uuid",
      nullable: true);

    migrationBuilder.AddColumn<string>(
      name: "Note",
      schema: "inventory",
      table: "inventory_movements",
      type: "character varying(240)",
      maxLength: 240,
      nullable: true);

    migrationBuilder.CreateIndex(
      name: "ix_inventory_movements_business_id_branch_id_sale_id",
      schema: "inventory",
      table: "inventory_movements",
      columns: ["BusinessId", "BranchId", "SaleId"]);
  }

  protected override void Down(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.DropIndex(
      name: "ix_inventory_movements_business_id_branch_id_sale_id",
      schema: "inventory",
      table: "inventory_movements");

    migrationBuilder.DropColumn(
      name: "SaleId",
      schema: "inventory",
      table: "inventory_movements");

    migrationBuilder.DropColumn(
      name: "Note",
      schema: "inventory",
      table: "inventory_movements");
  }
}
