// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SaasCommerce.BuildingBlocks.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202605270001_AddPurchaseProcessingState")]
public partial class AddPurchaseProcessingState : Migration
{
  protected override void Up(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.AddColumn<DateTimeOffset>(
      name: "CompletedAt",
      schema: "purchasing",
      table: "purchases",
      type: "timestamp with time zone",
      nullable: true);

    migrationBuilder.AddColumn<DateTimeOffset>(
      name: "FailedAt",
      schema: "purchasing",
      table: "purchases",
      type: "timestamp with time zone",
      nullable: true);

    migrationBuilder.AddColumn<string>(
      name: "FailureReason",
      schema: "purchasing",
      table: "purchases",
      type: "character varying(500)",
      maxLength: 500,
      nullable: true);
  }

  protected override void Down(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.DropColumn(
      name: "CompletedAt",
      schema: "purchasing",
      table: "purchases");

    migrationBuilder.DropColumn(
      name: "FailedAt",
      schema: "purchasing",
      table: "purchases");

    migrationBuilder.DropColumn(
      name: "FailureReason",
      schema: "purchasing",
      table: "purchases");
  }
}
