// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SaasCommerce.BuildingBlocks.Infrastructure.Persistence.Migrations;

/// <summary>
/// Normalizes column casing across <c>identity.audit_logs</c>, <c>identity.users</c>
/// and the <c>settings.*</c> tables to PascalCase, matching the EF Core default
/// convention used by every other module. Earlier migrations introduced
/// snake_case column names by mistake, which broke SELECT/UPDATE queries because
/// the entity configurations never declared <c>HasColumnName</c> overrides.
/// </summary>
[DbContext(typeof(AppDbContext))]
[Migration("202605200002_NormalizeColumnCasing")]
public partial class NormalizeColumnCasing : Migration
{
  protected override void Up(MigrationBuilder migrationBuilder)
  {
    // ── identity.users ───────────────────────────────────────────────────────
    migrationBuilder.RenameColumn(
      name: "must_change_password",
      schema: "identity",
      table: "users",
      newName: "MustChangePassword");

    // ── identity.audit_logs ──────────────────────────────────────────────────
    RenameColumns(migrationBuilder, "identity", "audit_logs", new[]
    {
      ("id", "Id"),
      ("business_id", "BusinessId"),
      ("user_id", "UserId"),
      ("action", "Action"),
      ("entity_name", "EntityName"),
      ("entity_id", "EntityId"),
      ("description", "Description"),
      ("ip_address", "IpAddress"),
      ("created_at", "CreatedAt"),
      ("correlation_id", "CorrelationId"),
      ("user_agent", "UserAgent"),
      ("metadata_json", "MetadataJson"),
    });

    // ── settings.business_settings ───────────────────────────────────────────
    RenameColumns(migrationBuilder, "settings", "business_settings", new[]
    {
      ("business_id", "BusinessId"),
      ("commercial_name", "CommercialName"),
      ("legal_name", "LegalName"),
      ("rnc", "Rnc"),
      ("phone", "Phone"),
      ("email", "Email"),
      ("address", "Address"),
      ("currency", "Currency"),
      ("timezone", "Timezone"),
      ("logo_url", "LogoUrl"),
      ("receipt_footer_text", "ReceiptFooterText"),
      ("updated_by", "UpdatedBy"),
      ("updated_at", "UpdatedAt"),
    });

    // ── settings.sales_settings ──────────────────────────────────────────────
    RenameColumns(migrationBuilder, "settings", "sales_settings", new[]
    {
      ("business_id", "BusinessId"),
      ("allow_negative_stock", "AllowNegativeStock"),
      ("allow_discounts", "AllowDiscounts"),
      ("require_customer_for_credit_sale", "RequireCustomerForCreditSale"),
      ("default_payment_method", "DefaultPaymentMethod"),
      ("enable_receipt_print_after_sale", "EnableReceiptPrintAfterSale"),
      ("enable_invoice_auto_generation", "EnableInvoiceAutoGeneration"),
      ("updated_by", "UpdatedBy"),
      ("updated_at", "UpdatedAt"),
    });

    // ── settings.inventory_settings ──────────────────────────────────────────
    RenameColumns(migrationBuilder, "settings", "inventory_settings", new[]
    {
      ("business_id", "BusinessId"),
      ("enable_low_stock_alerts", "EnableLowStockAlerts"),
      ("default_low_stock_threshold", "DefaultLowStockThreshold"),
      ("require_reason_for_inventory_adjustment", "RequireReasonForInventoryAdjustment"),
      ("allow_inventory_transfer_between_branches", "AllowInventoryTransferBetweenBranches"),
      ("updated_by", "UpdatedBy"),
      ("updated_at", "UpdatedAt"),
    });

    // ── settings.billing_settings ────────────────────────────────────────────
    RenameColumns(migrationBuilder, "settings", "billing_settings", new[]
    {
      ("business_id", "BusinessId"),
      ("receipt_header_text", "ReceiptHeaderText"),
      ("receipt_footer_text", "ReceiptFooterText"),
      ("show_logo_on_receipt", "ShowLogoOnReceipt"),
      ("show_rnc_on_receipt", "ShowRncOnReceipt"),
      ("enable_invoice_auto_generation", "EnableInvoiceAutoGeneration"),
      ("invoice_prefix", "InvoicePrefix"),
      ("invoice_sequence_start", "InvoiceSequenceStart"),
      ("updated_by", "UpdatedBy"),
      ("updated_at", "UpdatedAt"),
    });
  }

  protected override void Down(MigrationBuilder migrationBuilder)
  {
    // ── settings.billing_settings ────────────────────────────────────────────
    RenameColumns(migrationBuilder, "settings", "billing_settings", new[]
    {
      ("BusinessId", "business_id"),
      ("ReceiptHeaderText", "receipt_header_text"),
      ("ReceiptFooterText", "receipt_footer_text"),
      ("ShowLogoOnReceipt", "show_logo_on_receipt"),
      ("ShowRncOnReceipt", "show_rnc_on_receipt"),
      ("EnableInvoiceAutoGeneration", "enable_invoice_auto_generation"),
      ("InvoicePrefix", "invoice_prefix"),
      ("InvoiceSequenceStart", "invoice_sequence_start"),
      ("UpdatedBy", "updated_by"),
      ("UpdatedAt", "updated_at"),
    });

    // ── settings.inventory_settings ──────────────────────────────────────────
    RenameColumns(migrationBuilder, "settings", "inventory_settings", new[]
    {
      ("BusinessId", "business_id"),
      ("EnableLowStockAlerts", "enable_low_stock_alerts"),
      ("DefaultLowStockThreshold", "default_low_stock_threshold"),
      ("RequireReasonForInventoryAdjustment", "require_reason_for_inventory_adjustment"),
      ("AllowInventoryTransferBetweenBranches", "allow_inventory_transfer_between_branches"),
      ("UpdatedBy", "updated_by"),
      ("UpdatedAt", "updated_at"),
    });

    // ── settings.sales_settings ──────────────────────────────────────────────
    RenameColumns(migrationBuilder, "settings", "sales_settings", new[]
    {
      ("BusinessId", "business_id"),
      ("AllowNegativeStock", "allow_negative_stock"),
      ("AllowDiscounts", "allow_discounts"),
      ("RequireCustomerForCreditSale", "require_customer_for_credit_sale"),
      ("DefaultPaymentMethod", "default_payment_method"),
      ("EnableReceiptPrintAfterSale", "enable_receipt_print_after_sale"),
      ("EnableInvoiceAutoGeneration", "enable_invoice_auto_generation"),
      ("UpdatedBy", "updated_by"),
      ("UpdatedAt", "updated_at"),
    });

    // ── settings.business_settings ───────────────────────────────────────────
    RenameColumns(migrationBuilder, "settings", "business_settings", new[]
    {
      ("BusinessId", "business_id"),
      ("CommercialName", "commercial_name"),
      ("LegalName", "legal_name"),
      ("Rnc", "rnc"),
      ("Phone", "phone"),
      ("Email", "email"),
      ("Address", "address"),
      ("Currency", "currency"),
      ("Timezone", "timezone"),
      ("LogoUrl", "logo_url"),
      ("ReceiptFooterText", "receipt_footer_text"),
      ("UpdatedBy", "updated_by"),
      ("UpdatedAt", "updated_at"),
    });

    // ── identity.audit_logs ──────────────────────────────────────────────────
    RenameColumns(migrationBuilder, "identity", "audit_logs", new[]
    {
      ("Id", "id"),
      ("BusinessId", "business_id"),
      ("UserId", "user_id"),
      ("Action", "action"),
      ("EntityName", "entity_name"),
      ("EntityId", "entity_id"),
      ("Description", "description"),
      ("IpAddress", "ip_address"),
      ("CreatedAt", "created_at"),
      ("CorrelationId", "correlation_id"),
      ("UserAgent", "user_agent"),
      ("MetadataJson", "metadata_json"),
    });

    // ── identity.users ───────────────────────────────────────────────────────
    migrationBuilder.RenameColumn(
      name: "MustChangePassword",
      schema: "identity",
      table: "users",
      newName: "must_change_password");
  }

  private static void RenameColumns(
    MigrationBuilder migrationBuilder,
    string schema,
    string table,
    (string OldName, string NewName)[] columns)
  {
    foreach (var (oldName, newName) in columns)
    {
      migrationBuilder.RenameColumn(
        name: oldName,
        schema: schema,
        table: table,
        newName: newName);
    }
  }
}
