// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SaasCommerce.BuildingBlocks.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202606290002_AddCustomerCedulaUniqueIndex")]
public partial class AddCustomerCedulaUniqueIndex : Migration
{
  protected override void Up(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.Sql(
      """
      CREATE UNIQUE INDEX ix_customers_business_id_cedula
      ON customers.customers ("BusinessId", "Cedula")
      WHERE "Cedula" IS NOT NULL;
      """);
  }

  protected override void Down(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.Sql(
      """
      DROP INDEX IF EXISTS customers.ix_customers_business_id_cedula;
      """);
  }
}
