namespace SaasCommerce.Modules.Catalog.Contracts.Requests;

public sealed record UpdateProductRequest(
  string ProductType,
  string Name,
  string? Description,
  string Sku,
  string? Barcode,
  Guid? CategoryId,
  Guid? BrandId,
  string UnitOfMeasure,
  decimal SalePrice,
  decimal CostPrice,
  decimal? WholesalePrice,
  decimal? MinSalePrice,
  string TaxCategory,
  decimal TaxRate,
  bool IsTaxIncluded,
  bool AllowsDiscount,
  bool TrackInventory,
  decimal? MinimumStock,
  decimal? MaximumStock,
  decimal? ReorderPoint,
  bool AllowNegativeStock,
  string? InternalCode,
  string? SupplierCode,
  Guid? ParentProductId,
  string? VariantName,
  string? AttributesJson,
  bool IsActive = true);
